ALTER TYPE "ProductStatus" ADD VALUE IF NOT EXISTS 'PENDING' BEFORE 'ACTIVE';
ALTER TYPE "ProductStatus" ADD VALUE IF NOT EXISTS 'REJECTED' AFTER 'ACTIVE';
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED');
ALTER TABLE "User" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';
CREATE INDEX "User_status_idx" ON "User"("status");
