import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, CalendarClock, Check, TicketPercent, ToggleLeft, ToggleRight, Trash2 } from 'lucide-react';
import { useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { AuthRequired } from '../components/AuthRequired';
import { PageLoader } from '../components/PageState';
import { useDocumentTitle } from '../hooks/useDocumentTitle';
import { Button } from '../components/ui/Button';
import { api, ApiError, type Coupon, type User } from '../lib/api';
import { money } from '../lib/utils';

export function AdminCouponsPage() {
  useDocumentTitle('Coupons');
  const queryClient = useQueryClient(); const [message, setMessage] = useState(''); const formRef = useRef<HTMLFormElement>(null);
  const me = useQuery({ queryKey: ['me'], queryFn: () => api<{ user: User }>('/auth/me'), retry: false });
  const coupons = useQuery({ queryKey: ['admin-coupons'], queryFn: () => api<{ coupons: Coupon[] }>('/admin/coupons'), enabled: me.data?.user.role === 'ADMIN' });
  const create = useMutation({ mutationFn: (data: Record<string, unknown>) => api<{ coupon: Coupon }>('/admin/coupons', { method: 'POST', body: JSON.stringify(data) }), onSuccess: async ({ coupon }) => { setMessage(`${coupon.code} created`); formRef.current?.reset(); await queryClient.invalidateQueries({ queryKey: ['admin-coupons'] }); } });
  const toggle = useMutation({ mutationFn: ({ id, active }: { id: string; active: boolean }) => api<{ coupon: Coupon }>(`/admin/coupons/${id}`, { method: 'PATCH', body: JSON.stringify({ active }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['admin-coupons'] }) });
  const remove = useMutation({ mutationFn: (id: string) => api<void>(`/admin/coupons/${id}`, { method: 'DELETE' }), onSuccess: async () => { setMessage('Coupon deleted'); await queryClient.invalidateQueries({ queryKey: ['admin-coupons'] }); } });
  if (me.error instanceof ApiError && me.error.status === 401) return <AuthRequired title="Sign in to manage coupons"/>;
  if (me.isLoading) return <PageLoader label="Checking administrator access…"/>;
  if (me.data?.user.role !== 'ADMIN') return <main className="container-shell py-24 text-center"><h1 className="font-display text-4xl font-bold">Administrator access required</h1></main>;
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setMessage(''); const form = new FormData(event.currentTarget);
    const expires = String(form.get('expiresAt') ?? ''); const maxDiscount = String(form.get('maxDiscount') ?? ''); const usageLimit = String(form.get('usageLimit') ?? '');
    create.mutate({ code: form.get('code'), type: form.get('type'), value: Number(form.get('value')), minOrderAmount: Number(form.get('minOrderAmount') || 0), maxDiscount: maxDiscount ? Number(maxDiscount) : null, usageLimit: usageLimit ? Number(usageLimit) : null, expiresAt: expires ? new Date(`${expires}T23:59:59`).toISOString() : null, active: true });
  };
  const input = 'min-w-0 w-full rounded-xl border border-ink/12 bg-white px-4 py-3 outline-none focus:border-nile';
  return <main className="container-shell py-12"><Link to="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-nile"><ArrowLeft size={16}/>Back to Admin Panel</Link><div className="mt-6"><p className="text-sm font-bold uppercase tracking-[.18em] text-nile">Promotions</p><h1 className="mt-2 font-display text-5xl font-bold">Coupon management</h1><p className="mt-2 text-ink/50">Create controlled marketplace discounts with schedules and usage limits.</p></div>
    <div className="mt-9 grid items-start gap-7 lg:grid-cols-[380px_1fr]"><form ref={formRef} onSubmit={submit} className="grid gap-4 rounded-2xl border border-ink/8 bg-white p-6"><h2 className="font-display text-2xl font-bold">Create coupon</h2><label className="grid gap-1.5 text-sm font-medium">Code<input name="code" className={`${input} uppercase`} required minLength={3} maxLength={40} placeholder="NILE20"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Type<select name="type" className={input}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select></label><label className="grid gap-1.5 text-sm font-medium">Value<input name="value" className={input} type="number" inputMode="decimal" min="1" step="0.01" required/></label></div><label className="grid gap-1.5 text-sm font-medium">Minimum order<input name="minOrderAmount" className={input} type="number" inputMode="decimal" min="0" step="0.01" defaultValue="0"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Maximum discount<input name="maxDiscount" className={input} type="number" inputMode="decimal" min="1" step="0.01" placeholder="Optional"/></label><label className="grid gap-1.5 text-sm font-medium">Usage limit<input name="usageLimit" className={input} type="number" inputMode="numeric" min="1" step="1" placeholder="Unlimited"/></label></div><label className="grid gap-1.5 text-sm font-medium">Expires on<input name="expiresAt" className={input} type="date"/></label>{create.error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{create.error instanceof Error ? create.error.message : 'Could not create coupon'}</p>}{message && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700"><Check size={16}/>{message}</p>}<Button disabled={create.isPending}><TicketPercent size={17}/>{create.isPending ? 'Creating…' : 'Create coupon'}</Button></form>
      <section><h2 className="font-display text-3xl font-bold">Marketplace coupons</h2>{(toggle.error || remove.error) && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{(toggle.error ?? remove.error) instanceof Error ? (toggle.error ?? remove.error)?.message : 'Could not update the coupon'}</p>}<div className="mt-5 grid gap-4">{coupons.data?.coupons.map((coupon) => { const expired = coupon.expiresAt && new Date(coupon.expiresAt) <= new Date(); return <article key={coupon.id} className="rounded-2xl border border-ink/8 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h3 className="font-display text-2xl font-bold">{coupon.code}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${coupon.active && !expired ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{expired ? 'EXPIRED' : coupon.active ? 'ACTIVE' : 'PAUSED'}</span></div><p className="mt-2 text-sm text-ink/55">{coupon.type === 'PERCENTAGE' ? `${Number(coupon.value)}% off` : `${money(coupon.value)} off`} · Minimum {money(coupon.minOrderAmount)}</p>{coupon.expiresAt && <p className="mt-1 flex items-center gap-1 text-xs text-ink/40"><CalendarClock size={13}/>Expires {new Date(coupon.expiresAt).toLocaleDateString('en-EG')}</p>}</div><div className="flex items-center gap-3"><button disabled={toggle.isPending || Boolean(expired)} onClick={() => toggle.mutate({ id: coupon.id, active: !coupon.active })} className="flex items-center gap-2 text-sm font-semibold text-nile disabled:opacity-40">{coupon.active ? <ToggleRight size={27}/> : <ToggleLeft size={27}/>} {coupon.active ? 'Pause' : 'Activate'}</button><button disabled={remove.isPending} onClick={() => { if (window.confirm(`Delete ${coupon.code}? Existing orders will keep their recorded discount.`)) remove.mutate(coupon.id); }} className="grid size-9 place-items-center rounded-full text-ink/40 transition hover:bg-red-50 hover:text-red-600 disabled:opacity-40" aria-label={`Delete ${coupon.code}`}><Trash2 size={17}/></button></div></div><div className="mt-4 flex flex-wrap gap-6 border-t border-ink/8 pt-4 text-xs text-ink/50"><span><strong className="text-ink">{coupon.usedCount}</strong> uses</span><span>{coupon.usageLimit ? `${Math.max(coupon.usageLimit - coupon.usedCount, 0)} remaining` : 'Unlimited uses'}</span>{coupon.maxDiscount && <span>Cap {money(coupon.maxDiscount)}</span>}</div></article>; })}{coupons.isLoading && <p className="py-16 text-center text-ink/45">Loading coupons…</p>}{!coupons.isLoading && !coupons.data?.coupons.length && <div className="rounded-2xl bg-sand py-16 text-center"><TicketPercent className="mx-auto text-nile"/><h3 className="mt-3 font-display text-2xl font-bold">No coupons yet</h3></div>}</div></section></div>
  </main>;
}
