import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, LockKeyhole } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AuthRequired } from '../components/AuthRequired';
import { Button } from '../components/ui/Button';
import { api, ApiError, type Cart, type Order } from '../lib/api';
import { money } from '../lib/utils';

export function CheckoutPage() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [errorMessage, setErrorMessage] = useState('');
  const { data, isLoading, error } = useQuery({ queryKey: ['cart'], queryFn: () => api<{ cart: Cart }>('/cart'), retry: false });
  const checkout = useMutation({ mutationFn: (body: Record<string, FormDataEntryValue>) => api<{ order: Order }>('/checkout', { method: 'POST', body: JSON.stringify(body) }), onSuccess: async ({ order }) => { await queryClient.invalidateQueries({ queryKey: ['cart'] }); navigate(`/orders?placed=${order.orderNumber}`); }, onError: (err) => setErrorMessage(err instanceof Error ? err.message : 'Checkout failed') });
  if (error instanceof ApiError && error.status === 401) return <AuthRequired title="Sign in to check out"/>;
  if (isLoading) return <main className="container-shell py-20">Preparing checkout…</main>;
  const items = data?.cart.items ?? []; const subtotal = items.reduce((sum, item) => sum + Number(item.product.price) * item.quantity, 0); const shipping = subtotal >= 1500 ? 0 : 75;
  if (!items.length) return <main className="container-shell py-20 text-center"><CheckCircle2 className="mx-auto text-nile" size={42}/><h1 className="mt-5 font-display text-4xl font-bold">Your cart is empty</h1><Button className="mt-6" asChild><Link to="/shop">Continue shopping</Link></Button></main>;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setErrorMessage(''); checkout.mutate(Object.fromEntries(new FormData(event.currentTarget))); };
  const input = 'rounded-xl border border-ink/12 bg-white px-4 py-3 outline-none focus:border-nile';
  return <main className="container-shell py-14"><div className="flex items-center gap-2 text-sm font-semibold text-nile"><LockKeyhole size={17}/> Secure checkout</div><h1 className="mt-2 font-display text-5xl font-bold">Delivery details</h1><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_380px]"><form onSubmit={submit} className="grid gap-5 rounded-[1.5rem] border border-ink/10 bg-white p-6 sm:grid-cols-2 sm:p-8"><label className="grid gap-1.5 text-sm font-medium">Full name<input className={input} name="shippingName" required minLength={2}/></label><label className="grid gap-1.5 text-sm font-medium">Phone number<input className={input} name="shippingPhone" required minLength={8}/></label><label className="grid gap-1.5 text-sm font-medium sm:col-span-2">Street address<input className={input} name="shippingAddress" required minLength={8}/></label><label className="grid gap-1.5 text-sm font-medium">City<input className={input} name="shippingCity" required/></label><label className="grid gap-1.5 text-sm font-medium">Governorate<input className={input} name="shippingRegion" required/></label><label className="grid gap-1.5 text-sm font-medium sm:col-span-2">Delivery notes (optional)<textarea className={`${input} min-h-24 resize-y`} name="notes" maxLength={500}/></label><div className="sm:col-span-2"><div className="mb-5 rounded-xl bg-sand p-4 text-sm"><strong>Payment:</strong> Cash on delivery</div>{errorMessage && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{errorMessage}</p>}<Button className="w-full" size="lg" disabled={checkout.isPending}>{checkout.isPending ? 'Placing order…' : `Place order · ${money(subtotal + shipping)}`}</Button></div></form>
    <aside className="h-fit rounded-[1.5rem] bg-sand p-6"><h2 className="font-display text-2xl font-bold">Your order</h2><div className="mt-5 grid gap-4">{items.map((item) => <div key={item.id} className="flex gap-3"><img src={item.product.imageUrl} alt="" className="size-14 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.product.name}</p><p className="text-xs text-ink/50">Qty {item.quantity}</p></div><span className="text-sm font-semibold">{money(Number(item.product.price) * item.quantity)}</span></div>)}</div><dl className="mt-6 grid gap-3 border-t border-ink/10 pt-5 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div><div className="flex justify-between"><dt>Shipping</dt><dd>{shipping ? money(shipping) : 'Free'}</dd></div><div className="flex justify-between text-lg font-bold"><dt>Total</dt><dd>{money(subtotal + shipping)}</dd></div></dl></aside></div></main>;
}

